config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :deliveries
  resources :pizzas
  resources :recipes
  resources :crusts
  resources :ingredients
  resources :users

  root to: 'application#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
has_many :pizza
has_many :ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.fetch(:recipe, {})
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">

  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
    /* Make the image fully responsive */

  </style>
</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">




    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= image_tag('logo.png', width: '150px')%><a class="btn btn-info" style="color:#ffffff" href="/">Home</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>




        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/">Shopping Cart</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>

          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#7c0a02;'%></li>


          </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

        </ul>

        </div>


  </div>
</nav>

<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>


<div class="container">

  <div class="jumbotron">


        <%= image_tag('pizza_hut.jpg', width: '250px')%>
        <div class="card-body">
          <h4 class="card-title">  <%= @recipe.name %> </h4>
          <h4 class="card-title">  Info:<%= @recipe.info %> </h4>
          <h4 class="card-title"> Price: <%= @recipe.price %> </h4>

          <%= link_to 'Add to cart', new_pizza_path(p_id: @recipe.id,r_id:@recipe.name) %>







        </div>
      </div>
    </div>